repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: requirements-txt-fixer
      name: Requirements
      types: [file]
      exclude_types: ['image']
    - id: debug-statements
      name: Debugging
      language: python
      types: [file, python]
      exclude_types: ['image']
      language_version: python3.10
    - id: trailing-whitespace
      name: Trailing Whitespace
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: end-of-file-fixer
      name: EOF Newlines
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: check-yaml
      name: YAML Structure
      language: python
      args: ['--unsafe']
    - id: check-toml
      name: TOML Structure
    - id: check-merge-conflict
      name: Merge Conflicts
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      name: Black Formatting
      language: python
      types: [file, python]
      language_version: python3.10
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      name: flake8 Formatting
      language: python
      types: [file, python]
      args: [--ignore=E203 E301 E302 E501 E402 E704 W503 W504]
      additional_dependencies:
        - flake8-annotations
        - flake8-bandit
        - flake8-docstrings
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-raise
        - flake8-deprecated
        - flake8-print
        - git+https://github.com/python-formate/flake8-dunder-all
      language_version: python3.10
#  - repo: https://github.com/pycqa/isort
#    rev: 5.11.4
#    hooks:
#      - id: isort
#        name: isort Formatting
#        language: python
#        types: [file, python]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    - id: autoflake
ci:
  autoupdate_branch: "unstable"
  autofix_prs: true
  autoupdate_commit_msg: "ci: weekly check."
  autoupdate_schedule: weekly
  autofix_commit_msg: "ci: correct from checks."
